modLoader = "javafml"
loaderVersion = "[1,)"

license = "UNLICENSED"

[[mods]]
modId = "crabclaws"
version = "${version}"

displayName = "Crab Claws"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/crab-claws"

authors = "lupiiin_, luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Place/Break blocks from a distance with these Crab Claws!"

logoFile = "assets/crabclaws/icon.png"

[[mixins]]
config = "crabclaws.mixins.json"

[[dependencies.crabclaws]]
modId = "neoforge"
mandatory = true
versionRange = "[20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crabclaws]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crabclaws]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
